{
 "title": "NewsSubscribe Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "RDS CPUUtilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "news-rds" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "auto",
     "queryMode": "Metrics",
     "region": "ap-northeast-2",
     "stat": "Average",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "메일 전송 성공",
   "type": "logs",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /Success/\n| sort @timestamp desc\n| limit 20\n",
     "logGroups": [
      {
       "accountId": "635140758252",
       "arn": "arn:aws:logs:ap-northeast-2:635140758252:log-group:/aws/lambda/news-lambda-handler:*",
       "name": "/aws/lambda/news-lambda-handler"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "메일 전송 실패",
   "type": "logs",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /Fail/\n| sort @timestamp desc\n| limit 20\n",
     "logGroups": [
      {
       "accountId": "635140758252",
       "arn": "arn:aws:logs:ap-northeast-2:635140758252:log-group:/aws/lambda/news-lambda-handler:*",
       "name": "/aws/lambda/news-lambda-handler"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS FreeableMemory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "news-rds" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "auto",
     "queryMode": "Metrics",
     "region": "ap-northeast-2",
     "stat": "Average",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "크롤링 성공",
   "type": "logs",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /Crawling completed/\n| sort @timestamp desc\n| limit 20\n",
     "logGroups": [
      {
       "accountId": "635140758252",
       "arn": "arn:aws:logs:ap-northeast-2:635140758252:log-group:/aws/lambda/news-crawler-lambda:*",
       "name": "/aws/lambda/news-crawler-lambda"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Replica Lag (s)",
   "type": "gauge",
   "description": "RDS ReplicaLag은 장애 발생 시에만 표시됩니다.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "news-rds" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "period": "auto",
     "queryMode": "Metrics",
     "region": "ap-northeast-2",
     "stat": "Maximum",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NATGateway_유입량",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "NatGatewayId": "*" },
     "metricName": "ConnectionAttemptCount",
     "namespace": "AWS/NATGateway",
     "period": "auto",
     "queryMode": "Metrics",
     "region": "ap-northeast-2",
     "stat": "Maximum",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "크롤링 삭제",
   "type": "logs",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /뉴스 삭제 시작/\n| sort @timestamp desc\n| limit 20",
     "logGroups": [
      {
       "accountId": "635140758252",
       "arn": "arn:aws:logs:ap-northeast-2:635140758252:log-group:/aws/lambda/news-crawler-lambda:*",
       "name": "/aws/lambda/news-crawler-lambda"
      }
     ],
     "queryMode": "Logs",
     "region": "ap-northeast-2",
     "statistic": "Average"
    }
   ]
  }
 ]
}